# .github/workflows/deploy.yml

name: Deploy Log Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Deploy with Docker Compose
      run: |
        docker-compose -f docker-compose.yaml up -d  
